spring:
  profiles:
    active:
      -   dev
  
---
spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-config-felix-dev
---
spring:
  profiles: dev #测试环境
  application:
    name: microservicecloud-config-felix-test
# 请保存为 UTF-8 格式