spring:          
  profiles:
    active:
      - dev
---
server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: com.felix.springcloud.entities  # 所有 Entity 别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                 # mapper 映射文件
  
spring:
  profiles: dev
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource        # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver          # mysql驱动包
    url: jdbc:mysql://192.168.33.11:3306/cloudDB01           # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                       # 数据库连接池的最小维持连接数
      initial-size: 5                                   # 初始化连接数
      max-total: 5                                      # 最大连接数
      max-wait-millis: 200                              # 等待连接获取的最大超时时间
      
eureka:
  client: # 客户端注册进 eureka 服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: microservicecloud-dept8001-dev   #自定义服务名称信息
    prefer-ip-address: true                   #访问路径可以显示 IP地址 
      
info:
  app.name: felix-microservicecloud
  company.name: www.felix.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
      
---
server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: com.felix.springcloud.entities  # 所有 Entity 别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                 # mapper 映射文件
   
    
spring:
  profiles: test
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource        # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver          # mysql驱动包
    url: jdbc:mysql://192.168.33.11:3306/cloudDB02           # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                       # 数据库连接池的最小维持连接数
      initial-size: 5                                   # 初始化连接数
      max-total: 5                                      # 最大连接数
      max-wait-millis: 200                              # 等待连接获取的最大超时时间
      
eureka:
  client: # 客户端注册进 eureka 服务列表内
    service-url:
      defaultZone:http://eureka7001.com:7001/eureka
  instance:
    instance-id: microservicecloud-dept8001-test   #自定义服务名称信息
    prefer-ip-address: true                   #访问路径可以显示 IP地址 
      
info:
  app.name: felix-microservicecloud
  company.name: www.felix.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
